name: MekWars Weekly CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"
jobs:
  publish-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout MekWars
        uses: actions/checkout@v5
        with:
          ref: upgrade-49.20
          path: MekWars

      - name: Checkout MegaMek
        uses: actions/checkout@v5
        with:
          repository: MegaMek/megamek
          ref: v0.49.20
          path: megamek

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Client
        working-directory: MekWars
        run: ./gradlew MekWarsClient:build

      - name: Build Server
        working-directory: MekWars
        run: ./gradlew MekWarsServer:build

      - name: Add private key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Remove old droplet
        run: "doctl compute droplet delete mekwars-weekly-server --force"

      - name: Deploy the app
        run: "doctl compute droplet create 'mekwars-weekly-server' --image ubuntu-24-04-x64 --size s-1vcpu-1gb --region nyc1 --project-id=$PROJECT_ID --ssh-keys=$SSH_KEY_ID --wait"
        env:
          SSH_KEY_ID: ${{secrets.SSH_KEY_ID}}
          PROJECT_ID: ${{secrets.PROJECT_ID}}

      - name: Assign IP
        run: "doctl compute reserved-ip-action assign $IP_ADDRESS $(doctl compute droplet get mekwars-weekly-server --template {{.ID}})"
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}

      - name: Add droplet to known hosts
        run: echo ssh-keyscan -t rsa $IP_ADDRESS ~/.ssh/known_hosts
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}

      - name: Copy files to droplet
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{secrets.IP_ADDRESS}}
          KEY: ${{secrets.SSH_PRIVATE_KEY}}
          TARGET: MekWars

      - name: Upload Client Release
        uses: actions/upload-artifact@v4
        with:
          name: mekwars-client-release
          path: ./MekWars/MekWarsClient/build/distributions/*.zip

      - name: Upload Server Release
        uses: actions/upload-artifact@v4
        with:
          name: mekwars-server-release
          path: ./MekWars/MekWarsServer/build/distributions/*.zip
