name: MekWars Weekly CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"
jobs:
  publish-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout MekWars
        uses: actions/checkout@v5
        with:
          ref: upgrade-49.20
          path: MekWars

      - name: Checkout MegaMek
        uses: actions/checkout@v5
        with:
          repository: MegaMek/megamek
          ref: v0.49.20
          path: megamek

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Client
        working-directory: MekWars
        run: ./gradlew MekWarsClient:build

      - name: Build Server
        working-directory: MekWars
        run: ./gradlew MekWarsServer:build

      - name: Upload Client Release
        uses: actions/upload-artifact@v4
        with:
          name: mekwars-client-release
          path: ./MekWars/MekWarsClient/build/distributions/*.zip

      - name: Upload Server Release
        uses: actions/upload-artifact@v4
        with:
          name: mekwars-server-release
          path: ./MekWars/MekWarsServer/build/distributions/*.zip
