name: MekWars Weekly CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"
jobs:
  publish-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout MekWars
        uses: actions/checkout@v5
        with:
          ref: main
          path: MekWars

      - name: Checkout MegaMek
        uses: actions/checkout@v5
        with:
          repository: MegaMek/megamek
          ref: ${{ vars.MEGAMEK_VERSION }}
          path: megamek

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Client
        working-directory: MekWars
        run: ./gradlew MekWarsClient:build

      - name: Build Server
        working-directory: MekWars
        run: ./gradlew MekWarsServer:build

      - name: Add private key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}
          SSH_PRIVATE_KEY: |
            ${{secrets.SSH_PRIVATE_KEY}}

      - name: Add droplet to known hosts
        run: echo "$(ssh-keyscan -t rsa $IP_ADDRESS)" >> ~/.ssh/known_hosts
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}

      - name: Shutdown mekwars
        run: |
          ssh root@$IP_ADDRESS "systemctl stop mekwars"
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}

      - name: Copy files to droplet
        run: |
          rsync -r ./MekWars/MekWarsServer/build/distributions/MekWarsServer-9.0.0.tar root@$IP_ADDRESS:/srv/
          ssh root@$IP_ADDRESS "cd /srv && rm -rf ./MekWars && tar -xvf ./MekWarsServer-9.0.0.tar && mv ./MekWarsServer-9.0.0 MekWars && chown -R mekwars:root ./MekWars"
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}
          PACKAGE_NAME: MekWarsServer-9.0.0

      - name: Start mekwars
        run: |
          ssh root@$IP_ADDRESS "systemctl start mekwars"
        env:
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}

      - name: Upload Client Release
        uses: actions/upload-artifact@v4
        with:
          name: mekwars-client-release
          path: ./MekWars/MekWarsClient/build/distributions/*.zip

      - name: Upload Server Release
        uses: actions/upload-artifact@v4
        with:
          name: mekwars-server-release
          path: ./MekWars/MekWarsServer/build/distributions/*.zip
